
package goodsprice.ui;

import goodsprice.model.Good;
import goodsprice.reports.HtmlFormater;
import goodsprice.reports.MonthYearReport;
import goodsprice.reports.ReportUtils;
import goodsprice.reports.Reporter;
import goodsprice.reports.StringFormater;
import java.text.ParseException;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Raitis
 */
public class ReportDialog extends javax.swing.JDialog {
private static final String ERRMSG="Set up other date field!";
    private List<Good> goods;
    private javax.swing.JFrame parent;
    /**
     * Creates new form ReportDialog
     */
    public ReportDialog( String reportTxt, javax.swing.JFrame parent, boolean modal) {
         super(parent, modal);
         this.parent = parent;
        initComponents();
        jLblValidation.setText("");
        jTextPane.setText(reportTxt);
    }
     public ReportDialog( List<Good> goods, javax.swing.JFrame parent, boolean modal) {
          super(parent, modal);
        
           this.parent = parent;
        initComponents();
        
        jLblValidation.setText("");
        this.goods = goods;
     
        Date startDate=null;
        //By default make Start Date 1Jan for current year, the End date current date.
        int yy = ReportUtils.getYearPart(new Date());
        startDate= new Date(yy, 0, 1);
      
        String reportTxt = null;
        //reportTxt = createReport(startDate, new Date());
        reportTxt = createReportHtml(startDate, new Date());
        //jTextPane.setContentType("text/html");
        jTextPane.setText(reportTxt);
    }

     private String createReport(Date startDate, Date endDate){
       Reporter reporter = new Reporter(goods);
                
        List<MonthYearReport> reports = reporter.getTimeReportForAllShops(startDate,endDate);
        StringFormater formater = new StringFormater();
        String reportTxt = formater.printFmtStr(reports);
        return reportTxt;
     }
     
     private String createReportHtml(Date startDate, Date endDate){
       Reporter reporter = new Reporter(goods);
                
        List<MonthYearReport> reports = reporter.getTimeReportForAllShops(startDate,endDate);
        HtmlFormater formater = new HtmlFormater();
        String reportTxt = formater.printFmtStr_1(reports);
        return reportTxt;
     }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTxtStartDate = new javax.swing.JTextField();
        jBtnStartDate = new javax.swing.JButton();
        jTxtEndDate = new javax.swing.JTextField();
        jBtnEndDate = new javax.swing.JButton();
        jBtnUpdate = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane = new javax.swing.JTextPane();
        jLblValidation = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Report");

        jTxtStartDate.setEditable(false);
        jTxtStartDate.setToolTipText("Start Date");

        jBtnStartDate.setText("Pick Date");
        jBtnStartDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnStartDateActionPerformed(evt);
            }
        });

        jTxtEndDate.setEditable(false);
        jTxtEndDate.setToolTipText("End Date");

        jBtnEndDate.setText("Pick Date");
        jBtnEndDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEndDateActionPerformed(evt);
            }
        });

        jBtnUpdate.setText("Update");
        jBtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUpdateActionPerformed(evt);
            }
        });

        jTextPane.setEditable(false);
        jTextPane.setContentType("text/html"); // NOI18N
        jTextPane.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jScrollPane2.setViewportView(jTextPane);

        jLblValidation.setForeground(new java.awt.Color(255, 0, 51));
        jLblValidation.setText("Error text");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLblValidation, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnUpdate))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTxtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnStartDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnEndDate)
                        .addGap(0, 36, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnStartDate)
                    .addComponent(jTxtEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnEndDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnUpdate)
                    .addComponent(jLblValidation))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnStartDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnStartDateActionPerformed
        jTxtStartDate.setText(new DatePicker(this.parent,-1,-1).setPickedDate());
        if(jTxtEndDate.getText().isEmpty()){
          jLblValidation.setText(ERRMSG);
        }else {
           jLblValidation.setText("");
        }
    }//GEN-LAST:event_jBtnStartDateActionPerformed

    private void jBtnEndDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEndDateActionPerformed
        jTxtEndDate.setText(new DatePicker(this.parent,-1,-1).setPickedDate());
        if(jTxtStartDate.getText().isEmpty()){
          jLblValidation.setText(ERRMSG);
        }else {
           jLblValidation.setText("");
        }
    }//GEN-LAST:event_jBtnEndDateActionPerformed

    private void jBtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUpdateActionPerformed
        if (jTxtStartDate.getText().isEmpty()
                || jTxtEndDate.getText().isEmpty()) {
            return;
        }
        DateLabelFormatter formater = new DateLabelFormatter();

        Date startDate = null;
        Date endDate = null;
        try {
            startDate = formater.stringToValue(jTxtStartDate.getText());
            endDate = formater.stringToValue(jTxtEndDate.getText());
        } catch (ParseException ex) {
            Logger.getLogger(ReportDialog.class.getName()).log(Level.SEVERE, null, ex);
            return;
        }
        //String reportTxt = createReport(startDate, endDate);
         String reportTxt = createReportHtml(startDate, endDate);
        jTextPane.setText(reportTxt);
    }//GEN-LAST:event_jBtnUpdateActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportDialog("Test text",null,true).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnEndDate;
    private javax.swing.JButton jBtnStartDate;
    private javax.swing.JButton jBtnUpdate;
    private javax.swing.JLabel jLblValidation;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane;
    private javax.swing.JTextField jTxtEndDate;
    private javax.swing.JTextField jTxtStartDate;
    // End of variables declaration//GEN-END:variables
}
